#!/bin/bash

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

pattern="<!--- start usage output --->*<!--- end usage output --->"

substitution="$(cat <<EOF
<!--- start usage output --->
\`\`\`
$(COLUMNS=100 script/benchdiff --help)
\`\`\`
<!--- end usage output --->
EOF
)"

readme="$(cat README.md)"
echo "${readme//$pattern/$substitution}" > README.md
